### PR TITLE
Ignore columns

### PR DESCRIPTION
**Pull request by dandeezy**
This branch adds ignore column functionally by adding any columns you want this app to ignore via command line --ignore as many times as you want. These columns won't show up in diff but will be shown in patches! 

Lars, 
  I can't seem to be able to fix the tests. I don't know why csvdiff_cmd returns exit code -1 . The application works fine and I've manually tested it. Can you help me fix these few failing tests?

### CODE REVIEW

**Comment by dandeezy** [comment]
Added '--ignore', 'extra' parameters to csvdiff_cmd runner in tests. 
Tests still fail.

**Comment by larsyencken** [comment]
Hi Dan, thanks for the patch! I'm on summer break and without computer for
another week, I'll take a look once I'm back and see if I can work out why
the tests still fail. Just seeing the exit code being different is a little
frustrating, I agree.

**Comment by dandeezy** [comment]
No problem Lars, I’ll tell my team to pip install my branch zip. 

 

Enjoy your break! 

 

Talk to you later.

**Comment by larsyencken** [comment]
Ah, ok. Basically, the existing tests cover the loop of diffing `a.csv` and `b.csv` with csvdiff, generating a patch, then applying the patch to `a.csv` with csvpatch. It should be a closed loop that gives you the same result as `b.csv`.

In this case, you changed some of the test files, and needed to add the `--ignore` option to csvpatch too. I'd make new tests instead of changing the existing ones though.

In terms of the code change, a nicer way of doing this would be to use the ignored columns to create a view of the data that doesn't have those columns, when loading records. That way diffing or patching code doesn't need to change.

Got time to try and adjust your pull request, or would you like me to have a crack at this other approach?

**Comment by dandeezy** [comment]
Sure take a crack at it. That is a better way, I agree.

**Comment by kevinlr5** [comment]
I would like to give this a go...

**Comment by dandeezy** [comment]
@kevinlr5 go for it

**Comment by larsyencken** [comment]
Yeah, things have been more busy for me than I realised. Please take a stab at it!

**Comment by larsyencken** [comment]
Just merged https://github.com/larsyencken/csvdiff/pull/19 which implemented this in the view style. Thanks for prompting for this new feature.

**Pull request closed without merging**
